apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
spec:
  params:
    - name: dockerfile
      type: string
      description: "Path to the Dockerfile"
    - name: context
      type: string
      description: "Build context"
    - name: imageName
      type: string
      description: "Name for the built Docker image"
  workspaces:
    - name: source
  steps:
    - name: building
      image: docker:stable
      script: |
        #!/bin/sh
        until docker info >/dev/null 2>&1; do
            echo "Waiting for Docker to start..."
            sleep 1
        done
        docker build -f $(workspaces.source.path)/git-repo/$(params.dockerfile) -t $(params.imageName):latest $(workspaces.source.path)/git-repo/$(params.context)
  sidecars:
    - name: docker-daemon
      image: docker:stable-dind
      securityContext:
        privileged: true
      command:
        - dockerd
      args:
        - --host=unix:///var/run/docker.sock
        - --host=tcp://0.0.0.0:2375
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
  volumes:
    - name: dind-storage
      emptyDir: {}
