apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
spec:
  params:
    - name: dockerfile
      type: string
      description: "Path to the Dockerfile relative to the repository root"
    - name: context
      type: string
      description: "Build context"
    - name: imageName
      type: string
      description: "Name for the built Docker image"
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=/workspace/source/git-repo/$(params.dockerfile)
        - --context=/workspace/source/git-repo
        - --destination=$(params.imageName):latest
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
