apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-task
spec:
  params:
    - name: githubRepoURL
      type: string
      description: "The URL of the GitHub repository"
  workspaces:
    - name: output
  steps:
    - name: cloning
      image: alpine/git
      script: |
        #!/bin/sh
        if [ -d "$(workspaces.output.path)/git-repo" ]; then
          echo "Removing existing repository at $(workspaces.output.path)/git-repo"
          rm -rf $(workspaces.output.path)/git-repo
        fi
        git clone $(params.githubRepoURL) $(workspaces.output.path)/git-repo
