apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  config.json: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlkzTmhaekE1TlRwelpXTjFjbVZtYjNKaGJHeEFOVFE9IgoJCX0KCX0KfQ==
