apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-push-pipeline-run
spec:
  pipelineRef:
    name: build-and-push-pipeline
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: my-claim
  params:
    - name: githubRepoURL
      value: "https://github.com/Sarang095/Rails-DB-APP.git"
    - name: dockerfile
      value: "Dockerfile"
    - name: context
      value: "."
    - name: imageName
      value: "rails-db-app-web"
    - name: dockerHubUsername
      value: "csag095"
    - name: dockerHubPassword
      value: "secureforall@54"
