apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
spec:
  params:
    - name: githubRepoURL
      type: string
    - name: dockerfile
      type: string
    - name: context
      type: string
    - name: imageName
      type: string
    - name: dockerHubUsername
      type: string
    - name: dockerHubPassword
      type: string
  workspaces:
    - name: shared-workspace
    - name: my-secret
  tasks:
    - name: clone
      taskRef:
        name: clone-task
      params:
        - name: githubRepoURL
          value: $(params.githubRepoURL)
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build
      taskRef:
        name: build-task
      params:
        - name: dockerfile
          value: $(params.dockerfile)
        - name: context
          value: $(params.context)
        - name: imageName
          value: $(params.imageName)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: my-secret
