apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
spec:
  params:
    - name: githubRepoURL
      type: string
    - name: dockerfile
      type: string
    - name: context
      type: string
    - name: imageName
      type: string
    - name: dockerHubUsername
      type: string
    - name: dockerHubPassword
      type: string
  workspaces:
    - name: shared-workspace
    - name: my-secret
    - name: git-credentials
  tasks:
    - name: clone
      taskRef:
        name: clone-task
      params:
        - name: githubRepoURL
          value: $(params.githubRepoURL)
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build
      runAfter:
        - clone
      taskRef:
        name: kaniko
      params:
        - name: imageName
          value: $(params.imageName)
        - name: dockerfile
          value: $(params.dockerfile)
        - name: context
          value: $(params.context)
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: my-secret
          workspace: my-secret
    - name: update-yaml-and-push
      runAfter:
        - build
      taskRef:
        name: update-deployment-yaml
      params:
        - name: NEW_IMAGE
          value: $(params.imageName):latest
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: git-credentials
          workspace: git-credentials

