apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: full-permissions-binding
subjects:
- kind: ServiceAccount
  name: tekton-event-listener-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: full-permissions
  apiGroup: rbac.authorization.k8s.io

