apiVersion: v1
kind: Service
metadata:
  name: el-github-listener
  labels:
    app: tekton-triggers
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    eventlistener: github-listener

