apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - name: githubRepoURL
      description: The URL of the GitHub repository
    - name: dockerHubUsername
      description: Docker Hub username
    - name: dockerHubPassword
      description: Docker Hub password
    - name: imageName
      description: Docker Hub image name
    - name: dockerfile
      description: Path to Dockerfile
    - name: context
      description: Build context
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-and-push-pipeline-run-
      spec:
        pipelineRef:
          name: build-and-push-pipeline
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: my-claim
          - name: my-secret
            secret:
              secretName: my-secret
        params:
          - name: githubRepoURL
            value: https://github.com/Sarang095/Rails-DB-APP.git
          - name: dockerfile
            value: $(params.dockerfile)
          - name: context
            value: $(params.context)
          - name: imageName
            value: csag095/rails-db-app-web
          - name: dockerHubUsername
            value: $(params.dockerHubUsername)
          - name: dockerHubPassword
            value: $(params.dockerHubPassword)
        serviceAccountName: tekton-event-listener-sa
